/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import dbConnect.dbConnector;
import dbconnect.Session;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.PreparedStatement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 10
 */
public class U_Property extends javax.swing.JFrame {

    /**
     * Creates new form Property
     */
    public U_Property() {
        initComponents();
         setLocationRelativeTo(null);
       Session sess = Session.getInstance();
       
   
        
        
       
       
       

      
        ty.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateMembershipImage();
               
                
            }
        });

        
        
        updateMembershipImage();
    }

    public String destination = "";
    File selectedFile;
    public String oldpath;
    public String path;
    
    public void setPropertyTypeAndLoadImage(String type) {
   ty.setSelectedItem(type);
    updateMembershipImage();
}


public static int getHeightFromWidth(String imagePath, int desiredWidth) {
        try {
          
            File imageFile = new File(imagePath);
            BufferedImage image = ImageIO.read(imageFile);
            
        
            int originalWidth = image.getWidth();
            int originalHeight = image.getHeight();
            
          
            int newHeight = (int) ((double) desiredWidth / originalWidth * originalHeight);
            
            return newHeight;
        } catch (IOException ex) {
            System.out.println("No image found!");
        }
        
        return -1;
    }

public  ImageIcon ResizeImage(String ImagePath, byte[] pic, JLabel label) {
    ImageIcon MyImage = null;
        if(ImagePath !=null){
            MyImage = new ImageIcon(ImagePath);
        }else{
            MyImage = new ImageIcon(pic);
        }
        
    int newHeight = getHeightFromWidth(ImagePath, label.getWidth());

    Image img = MyImage.getImage();
    Image newImg = img.getScaledInstance(label.getWidth(), newHeight, Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}

public void updateMembershipImage() {
    String selectedType = (String) ty.getSelectedItem();
    String imagePath = null;

    if (selectedType != null) {
        switch (selectedType.trim()) {
            case "Commercial":
                imagePath = "src/imageshouse/1.jpg";
                break;
            case "Residential":
                imagePath = "src/imageshouse/2.jpg";
                break;
            case "Industrial":
                imagePath = "src/imageshouse/3.jpg";
                break;
            case "Mansion":
                imagePath = "src/imageshouse/7.jpg";
                break;
            default:
                image.setIcon(null);
                return;
        }

        File imageFile = new File(imagePath);
        if (imageFile.exists()) {
            ImageIcon rawIcon = new ImageIcon(imagePath);
            rawIcon.setDescription(imagePath); // ✅ Store the image path inside the icon

            // ✅ Set the resized image using ResizeImage
            ImageIcon resizedIcon = ResizeImage(imagePath, null, image);

            // ✅ Transfer the description (path) to the resized icon
            if (resizedIcon != null) {
                resizedIcon.setDescription(imagePath);
                image.setIcon(resizedIcon);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Image file not found: " + imagePath);
            image.setIcon(null);
        }
    } else {
        image.setIcon(null);
    }
}


 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ty = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pr = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        pid = new javax.swing.JTextField();
        stat = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        imagesss = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        st = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Property");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("ID :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 40, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Status :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 90, 30));

        ty.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Commercial", "Residential", "Industrial", "Land", "Mansion" }));
        jPanel3.add(ty, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 160, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Type :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 50, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total Price :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 30));
        jPanel3.add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, 30));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("BUY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 100, -1));

        pid.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        pid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pid.setBorder(null);
        pid.setEnabled(false);
        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        jPanel3.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 160, 40));

        stat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available" }));
        jPanel3.add(stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 160, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-48.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 40, 40));

        imagesss.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        imagesss.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 250));

        jPanel3.add(imagesss, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 340, 300));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Structure :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 80, 30));

        st.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Two-Story", "Single", "Two-Story" }));
        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });
        jPanel3.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 160, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 760, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
     this.dispose();
      PropertyTransaction PT = new PropertyTransaction();
      PT.setVisible(true);              // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if (ty.getSelectedItem() == null || st.getSelectedItem() == null || pr.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields are required.");
    } else {
        try {
            String pType = ty.getSelectedItem().toString().trim();
            String pStructure = st.getSelectedItem().toString().trim();
            int pPrice = Integer.parseInt(pr.getText().trim());

            File imageFileToCheck = selectedFile;

            // Check image from JLabel if none selected
            if (imageFileToCheck == null && image.getIcon() != null) {
                if (image.getIcon() instanceof ImageIcon) {
                    ImageIcon icon = (ImageIcon) image.getIcon();
                    String imagePath = icon.getDescription(); // should be set when loading image
                    if (imagePath != null) {
                        imageFileToCheck = new File(imagePath);
                    }
                }
            }

            if (imageFileToCheck == null || !imageFileToCheck.exists()) {
                JOptionPane.showMessageDialog(null, "No image selected or found.");
                return;
            }

            // Use ONLY the filename for matching DB record (because your DB stores just filenames)
            String imagePathInDB = imageFileToCheck.getName();

            dbConnector dbc = new dbConnector();

            // Update only available properties
            String updateQuery = "UPDATE properties SET status = 'Sold' WHERE type = ? AND structure = ? AND price = ? AND image = ? AND status = 'Available'";
            PreparedStatement pst = dbc.getConnection().prepareStatement(updateQuery);
            pst.setString(1, pType);
            pst.setString(2, pStructure);
            pst.setInt(3, pPrice);
            pst.setString(4, imagePathInDB);

            int updated = pst.executeUpdate();

            if (updated > 0) {
                JOptionPane.showMessageDialog(null, "Property successfully purchased (status set to Sold).");
                ty.setSelectedIndex(0);
                st.setSelectedIndex(0);
                pr.setText("");
                stat.setSelectedIndex(0);
                image.setIcon(null);
                selectedFile = null;
            } else {
                JOptionPane.showMessageDialog(null, "No matching property found or already sold.");
            }

            pst.close();
            dbc.closeConnection();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }
     this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U_Property.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U_Property.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U_Property.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U_Property.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U_Property().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel image;
    private javax.swing.JPanel imagesss;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextField pid;
    public javax.swing.JTextField pr;
    private javax.swing.JComboBox<String> st;
    private javax.swing.JComboBox<String> stat;
    public javax.swing.JComboBox<String> ty;
    // End of variables declaration//GEN-END:variables
}
