/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Logs.Login;
import User.AccountDetails;
import User.UserDashboard;
import dbConnect.dbConnector;
import dbconnect.Session;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 10
 */
public class E_Add_Recovery extends javax.swing.JFrame {
       private static String userImagePath = null;
       private static String i_username;
    
    
    
    /**
     * Creates new form Recovery
     */
    public E_Add_Recovery(String username, String imgPath) {
        initComponents();
        this.i_username = username;
        
        userImagePath = imgPath;
    }
      private void logActivity(int Iid, String action) {
        String sql = "INSERT INTO logs_table (i_id, logs_action, logs_date) VALUES (?, ?, NOW())";
        dbConnector db = new dbConnector();

        try (Connection conn = db.getConnection();
                PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setInt(1, Iid);
            pst.setString(2, action);
            pst.executeUpdate();
        } catch (SQLException e) {
            System.err.println("Error logging activity: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        acc_Iid = new javax.swing.JLabel();
        Back1 = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        sq = new javax.swing.JComboBox<>();
        ans = new javax.swing.JTextField();
        acc_fname = new javax.swing.JLabel();
        acc_lname = new javax.swing.JLabel();
        acc_username = new javax.swing.JLabel();
        acc_email = new javax.swing.JLabel();
        acc_cnum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setDoubleBuffered(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Password Recovery");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 60));

        acc_Iid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        acc_Iid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_Iid.setText("USER ID");
        jPanel1.add(acc_Iid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, -1));

        Back1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Back1.setText("Back");
        Back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back1MouseClicked(evt);
            }
        });
        jPanel1.add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 120, 40));

        Save.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Save.setText("Save");
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMouseClicked(evt);
            }
        });
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 130, 40));

        sq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What's the name of your first Girlfriend?", "What's the lastname of your Mother?", "What's your favorite Movie?", "What's your favorite Song?", "What's your favorite Sports?" }));
        jPanel1.add(sq, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 410, 30));
        jPanel1.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 410, 30));

        acc_fname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        acc_fname.setText("FirstName");
        jPanel1.add(acc_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 30));

        acc_lname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        acc_lname.setText("LastName");
        jPanel1.add(acc_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 240, 30));

        acc_username.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        acc_username.setText("UserName");
        jPanel1.add(acc_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 240, 30));

        acc_email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        acc_email.setText("Email");
        jPanel1.add(acc_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 240, 30));

        acc_cnum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        acc_cnum.setText("Phone ");
        jPanel1.add(acc_cnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 240, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseClicked
      AccountDetails ad = new AccountDetails(i_username, userImagePath);
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back1MouseClicked

    private void SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseClicked
 dbConnector dbc = new dbConnector();
        Session sess = Session.getInstance();
        String secQuestion = sq.getSelectedItem().toString();
        String secAnswer = ans.getText();
        dbConnector connector = new dbConnector();
        int userId = 0;
        String uname2 = null;

        if(secAnswer.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Fill All Boxes");
        }else
        {
            System.out.println("1");
            
//            dbc.updateData("UPDATE tbl_accounts SET security_question = '" + secQuestion + "', security_answer='" + secAnswer + "' WHERE u_id = '" + sess.getUid() + "'");
            
            System.out.println("2");
            System.out.println(""+sess.getIid());
            System.out.println(""+secQuestion);
            System.out.println(""+secAnswer);

            try 
            {
                String query = "UPDATE user SET security_question = ?, security_answer = ? WHERE i_id = ?";
                PreparedStatement pstmt2 = connector.getConnection().prepareStatement(query);
                pstmt2.setString(1, secQuestion);  // Set the value for the first parameter (security_question)
                pstmt2.setString(2, secAnswer);    // Set the value for the second parameter (security_answer)
                pstmt2.setInt(3, sess.getIid());   // Set the value for the third parameter (i_id)

                int rowsAffected = pstmt2.executeUpdate(); // Executes the update query
                if (rowsAffected > 0) {
                    System.out.println("Update successful.");
                    
                    logActivity(userId, "Updated account for user: " + i_username);
                    
                } else {
                    System.out.println("No rows updated.");
                }
                
                String query2 = "SELECT * FROM user WHERE i_id = '" + sess.getIid() + "'";
                PreparedStatement pstmt = connector.getConnection().prepareStatement(query2);

                ResultSet resultSet = pstmt.executeQuery();

                if (resultSet.next()) {
                    userId = resultSet.getInt("i_id");   // Update the outer `userId` correctly
                    uname2 = resultSet.getString("i_username");
                }
            } catch (SQLException ex) {
                System.out.println("SQL Exception: " + ex);
            }

            UserDashboard ud = new UserDashboard(i_username, userImagePath);
            ud.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_SaveMouseClicked

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed

    }//GEN-LAST:event_SaveActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
        if(sess.getIid() == 0)
        {
           JOptionPane.showMessageDialog(null, "No Account, Login First");
            Login l = new Login();
            l.setVisible(true);
            this.dispose();
        }else
        {
            acc_Iid.setText("ID :" + sess.getIid());
            acc_fname.setText("FirstName : " + sess.getFname());
            acc_lname.setText("LastName : " + sess.getLname());
            acc_username.setText("UserName : " + sess.getUsername());
            acc_email.setText("User Email : " + sess.getEmail());
            acc_cnum.setText("Phonenumber : " + sess.getPhone());
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_Add_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_Add_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_Add_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_Add_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String imgPath = "path/to/default/image.png";
                new E_Add_Recovery(i_username, imgPath).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back1;
    private javax.swing.JButton Save;
    private javax.swing.JLabel acc_Iid;
    public javax.swing.JLabel acc_cnum;
    public javax.swing.JLabel acc_email;
    private javax.swing.JLabel acc_fname;
    private javax.swing.JLabel acc_lname;
    private javax.swing.JLabel acc_username;
    private javax.swing.JTextField ans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> sq;
    // End of variables declaration//GEN-END:variables
}
